### ISSUE TITLE
Create a branch develop

### ISSUE THREAD

**Issue by Maharjan-Sunil** [Maharjan-Sunil/TravisCICD#4]
So that we won't merge directly with master.

**Comment by Maharjan-Sunil** [comment]
and fix the display message in home page with new branch

**Comment by Maharjan-Sunil** [comment]
![image](https://user-images.githubusercontent.com/34715139/72313020-11447880-36b2-11ea-95b8-c934eb6ce4d8.png)

**Comment by Maharjan-Sunil** [comment]
![image](https://user-images.githubusercontent.com/34715139/72313448-7a78bb80-36b3-11ea-9678-9bfd049fdd11.png)

**Comment by maharjan-sunil** [comment]
fixed 
![image](https://user-images.githubusercontent.com/34715139/72313580-e9eeab00-36b3-11ea-88ef-6ee2925784bd.png)
